### ISSUE TITLE
classification between coding and non-coding RNA?

### ISSUE THREAD

**Issue by BinhongLiu** [Bonidia/BioAutoML#3]
Hi,
    I have some ORF sequences from bacteria and archaea that need to be classified as protein-coding or noncoding ORFs. Could BioAutoML be used to do this work? If could, how should I set the ncRNA data for training? Could I just use the seven RNA sequences together (253+263+178+113+350+445+687), and mRNA sequences (702) from [your paper](https://academic.oup.com/bib/article/23/4/bbac218/6618238) for the binary training? Many thanks!
Best!

**Comment by Bonidia** [comment]
Dear BinhongLiu,

We hope this email finds you well!

Currently, BioAutoML can run on any problem with biological sequences (DNA/RNA/Protein).

You just need to pass a training set, so that it learns to work with new sequences.

So, you need to prepare a training dataset with non-coding and encoding sequences (there are several sequences available in the literature, but I can help if required). These already-known sequences will be passed as training and the new sequences that you want to classify will be passed as test. See the example below:

python BioAutoML-feature.py -fasta_train coding.fasta noncoding.fasta -fasta_label_train coding noncoding -fasta_test new_sequences.fasta -fasta_label_test unknown -output test_directory

Please feel free to reach out if you need anything.

Best regards,

Robson P Bonidia.

**Comment by Bonidia** [comment]
Dear BinhongLiu,

We hope this email finds you well!

**Non-coding examples:** You can merge all these sequences into a single fasta file that will be non-coding. 

1 - https://github.com/Bonidia/BioAutoML/tree/main/Case%20Studies/CS-I-A/E_coli - **Escherichia coli** - It is necessary to merge the files into a single Fasta.
2 - https://github.com/Bonidia/BioAutoML/tree/main/Case%20Studies/CS-I-A/S_enterica - **S enterica** - It is necessary to merge the files into a single Fasta.
3 - https://github.com/Bonidia/BioAutoML/tree/main/Case%20Studies/CS-I-B - **Other bacteria** - It is necessary to merge the files into a single Fasta.

**Coding examples:** You can merge all these sequences into a single fasta file that will be coding. 

1 - https://bacteria.ensembl.org/info/data/ftp/index.html
2 - https://ecocyc.org/

Let me know if it worked!

Please feel free to reach out if you need anything.

Best regards,

Robson P Bonidia.

**Comment by Bonidia** [comment]
Other coding sequences: https://github.com/Bonidia/BioAutoML/blob/main/Case%20Studies/CS-II/mRNA.fasta

**Comment by Bonidia** [comment]
Dear BinhongLiu,

We hope this email finds you well!

Let me know if it worked!

Please feel free to reach out if you need anything.

Best regards,

Robson P Bonidia.

**Comment by BinhongLiu** [comment]
Sure! I'm still downloading the cDNA sequences from here (https://bacteria.ensembl.org/info/data/ftp/index.html). It seems to need another few days to complete the downloading.
Thanks! Best!

**Comment by Bonidia** [comment]
Dear BinhongLiu,

We hope this email finds you well!

Let me know if it worked!

Please feel free to reach out if you need anything.

Best regards,

Robson P Bonidia.
